import { enhanceRealScene, trainingScene } from './visual-project-real';
const root=document.querySelector<HTMLElement>('#visual-project')!;
const $=(id:string)=>document.getElementById(id)!;
type Stage={name:string;title:string;summary:string;caption:string;limit:string;tools:string};
const data:Record<string,{type:string;title:string;question:string;outcome:string;stages:Stage[]}>={
citibike:{type:'骑行数据 → 站点需求 → 价格建议',title:'CitiBike',question:'一个站点在某个小时会借出、还入多少车？这些数量怎样转成价格建议？',outcome:'离线预测实验 ＋ 价格规则演示',stages:[
{name:'清洗记录',title:'先让骑行记录可用',summary:'原始记录清洗后，一行仍然是一次骑行。',caption:'示意数据：删除重复编号和缺少站点的记录。点击按钮查看变化。',limit:'实际输入约 1,453 万次骑行、16 个 CSV 文件。图中仅用少量虚构记录演示处理规则。',tools:'PySpark 读取、转换与去重；Parquet 保存 Bronze 中间结果。AI 辅助生成代码，程序按固定规则执行。'},
{name:'按站点汇总',title:'一次骑行，分别计入两个站点',summary:'借出按开始时间统计，还入按结束时间统计。',caption:'示意：A 站 08:50 借出，B 站 09:10 还入，分别进入两个小时。',limit:'Silver 共约 438.8 万条站点小时记录。Gold 做过标准化与 PCA，但最终训练直接读取 Silver。',tools:'按站点和小时分组计数，并加入时间、业务和天气字段。AI 协助编写聚合与字段生成代码。'},
{name:'分组训练',title:'数据分给三种用途',summary:'训练用来学习；验证供比较；测试用于评估。',caption:'每个色块代表一份示意数据。切换按钮比较随机分组与按时间分组。',limit:'原版随机切分；后续修复采用时间切分。图中 80/10/10 是比例示意，实际按不同小时划分时，行数比例不一定相同。',tools:'原版训练读取 Silver，随机森林从训练记录中学习。时间切分用于模拟过去训练、后续评估；字段是否提前可得仍需单独检查。'},
{name:'计算价格',title:'供需差变化，建议价随之变化',summary:'移动滑块，观察既定规则如何计算价格。',caption:'示意规则：缺车越多，价格倍率越高；这里展示规则计算，不是实时预测。',limit:'价格规则没有经过真实运营实验，不能证明提价会产生预期调节效果。',tools:'示意沿项目的基础价 4.49 美元和供需倍率表达。计算为 4.49 × (1 + 缺口/20)，本演示限制倍率不超过 1.5；不是调用线上服务。'},
{name:'接口与看板',title:'让规则结果可以被查询',summary:'请求指定站点与时间，接口返回示例价格，页面显示结果。',caption:'点击发送示例请求，观察请求与响应。',limit:'当前 API 从已有 CSV 读取均值或规则参考，没有接入离线 Spark 模型；图中的两部分明确分开。',tools:'FastAPI 提供接口，前端展示结果。AI 协助开发接口与页面；这段交互是浏览器内示意，没有请求项目后端。'},
{name:'复核与修复',title:'成绩下降，也揭示了评估问题',summary:'同样用 2.4 万行，比较三组冒烟测试。',caption:'借出量测试 R²：旧字段随机分组 0.633；去三字段随机分组 0.121；去三字段时间分组 0.095。',limit:'三组不是完整正式重训。第三组测试样本发生变化，差异不能全部归因于时间切分；天气字段仍需检查预测时可用性。',tools:'外部代码复核发现同小时电动车比例、会员比例和平均骑行时长的风险，再将要求传给工作台。修复采用删除三个字段、时间切分和冒烟测试；未部署新模型。'}]},
adventureworks:{type:'两张销售表 → 经营指标 → 问题定位',title:'AdventureWorks',question:'销售规模增长，是否同时带来了较好的估算毛利？',outcome:'三页 Power BI 经营看板',stages:[
{name:'合并渠道',title:'把两个渠道放进同一张明细表',summary:'统一字段后，上下追加，保留每条销售记录。',caption:'示意数据：蓝绿色为直销，橙色为经销商。点击合并，观察记录位置。',limit:'实际使用 Microsoft AdventureWorksDW2022 样例库，共 121,253 条销售明细；一行是一张订单中的一条商品记录。',tools:'SQL Server 还原官方备份；UNION ALL 按相同列顺序追加两张销售表，并加入渠道标记。AI 辅助生成 SQL。'},
{name:'检查记录',title:'找到问题，再判断怎样处理',summary:'按明细编号检查重复，按业务要求检查缺失。',caption:'示意表故意放入一条重复编号和一处缺失成本。点击检查定位问题。',limit:'这张表是检查机制演示，不是项目真实异常记录。真实项目还核对源表与统一表的行数、金额及关联情况。',tools:'SQL 统计异常与核对金额，Power Query 检查类型、空值和错误。重复是否异常取决于每行代表什么，不能直接按订单号删除明细。'},
{name:'关联说明表',title:'编号把销售与商品信息联系起来',summary:'选择一张说明表，看它通过哪个键关联销售明细。',caption:'选择“产品”，查看 ProductKey 怎样匹配到自行车名称。',limit:'四张说明表分别按键关联销售表；说明表的键应唯一，关系为一对多。',tools:'日期使用 OrderDateKey → DateKey；产品使用 ProductKey；地区使用 SalesTerritoryKey；促销使用 PromotionKey。AI 协助整理关系与模型说明。'},
{name:'计算指标',title:'选定范围，再计算收入与毛利',summary:'切换渠道，观察相同公式在不同记录范围内计算。',caption:'虚构小样本用于解释公式；以下金额不是项目汇总值。',limit:'估算毛利只扣除样例产品成本，没有扣除全部经营费用，不能当作净利润。',tools:'DAX 度量值按当前筛选范围求和。毛利率＝总估算毛利÷总收入，而不是每行毛利率的平均值。AI 辅助生成 DAX。'},
{name:'定位差异',title:'收入占比高，毛利贡献却低',summary:'经销商的两个占比形成明显差异。',caption:'实际项目结果：经销商贡献约 73.26% 收入、约 3.75% 估算毛利。',limit:'继续按年份与产品查看，发现 2013 年经销商自行车值得核查；关联差异不能直接证明原因。',tools:'Power BI 筛选和下钻，检查年份、渠道、产品及折扣组合。年度比较需注意数据覆盖范围；2013 年经销商数据未覆盖完整年度。'},
{name:'展示与复核',title:'把发现放进看板，把订单交给工作台',summary:'同一份销售数据，分别用于展示与订单级检查。',caption:'Power BI 使用商品明细；工作台使用按订单汇总的 31,455 行数据。',limit:'工作台检查通过，不代表整份 Power BI 文件已经完成独立审计；项目使用虚构企业样例。',tools:'经营总览、盈利诊断、区域分析三页 Power BI 看板。SQL 按渠道与订单编号汇总后导出工作台数据，AI 辅助实现查询、页面与说明。'}]}};
data.citibike.stages[0].limit='实际输入约 1,453 万次骑行、16 个 CSV。当前展示其中一条真实记录，保留原始编号。';
data.citibike.stages[1].title='把骑行事件，汇总成站点小时记录';
data.citibike.stages[3].tools='演示直接对应 pricing_engine.py 的车辆短缺、双余量折扣与正常价格分支。固定需求为借出 19、还入 11，固定空桩 29；滑块调整可用车辆。4.49 美元是项目代码的基础价。';
data.adventureworks.stages[0].caption='真实销售明细按渠道上下追加，保留每条记录。';
data.adventureworks.stages[1].limit='这里检查三条真实导出明细，检查结果只针对这三条；完整数据还有项目中的 SQL 检查结果。';
data.citibike.stages.splice(3,0,{name:'训练与评估',title:'从训练记录，到模型评估结果',summary:'模型学习训练集，再分别检查验证集与测试集。',caption:'动画解释训练过程；分支不代表保存模型的真实阈值。指标来自原版训练记录。',limit:'R²＝0.644 对应原版随机切分及旧字段，不代表修复后的成绩，也不是准确率。',tools:'PySpark MLlib 随机森林回归；训练集调用 fit，验证与测试集调用 transform，再计算指标。'});
let project='citibike';
const table=(heads:string[],rows:string[][],classes:string[]=[])=>`<table class="data-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr class="${classes[i]||''}" style="--i:${i}">${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const btn=(text:string,id:string,secondary=false)=>`<button id="${id}" class="${secondary?'secondary':''}">${text}</button>`;
const icon=(kind:string)=>`<svg viewBox="0 0 80 70" aria-hidden="true">${kind==='data'?'<rect x="15" y="10" width="50" height="50" rx="4"/><path d="M15 25h50M30 10v50M15 38h50M15 50h50"/>':kind==='screen'?'<rect x="5" y="8" width="70" height="44" rx="4"/><path d="M40 52v10M23 62h34M16 40l12-13 13 7 21-17"/>':'<path d="M26 14L8 35l18 21M54 14l18 21-18 21M46 10L34 60"/>'}</svg>`;

const clamp=(n:number)=>Math.max(0,Math.min(1,n));
let updates:Array<()=>void>=[];
function render(){
 const p=data[project];
 document.documentElement.style.setProperty('--accent',project==='citibike'?'#087f86':'#725137');
 document.documentElement.style.setProperty('--soft',project==='citibike'?'#dceee9':'#f0e8dc');
 for(const [id,text] of Object.entries({'project-type':p.type,'project-title':p.title,'project-question':p.question,'project-outcome':p.outcome}))$(id).textContent=text;
 document.querySelectorAll<HTMLButtonElement>('[data-project]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.project===project)));
 $('journey').innerHTML=p.stages.map((v,i)=>`<button data-step="${i}"><span>0${i+1}</span><strong>${v.name}</strong></button>`).join('');
 $('stories').innerHTML=p.stages.map((s,i)=>`<section class="story" id="stage-${i}" aria-labelledby="title-${i}"><div class="story-sticky"><div class="vp-stage"><header class="vp-stage-heading"><div><span>0${i+1} / ${p.stages.length}</span><h2 id="title-${i}">${s.title}</h2></div><p>${s.summary}</p></header><div class="story-progress"><i></i></div><div data-ui="scene" class="vp-scene"></div><div class="vp-controls"><div data-ui="scene-controls"></div></div><p data-ui="scene-caption">${s.caption.replace(/点击[^。]*。/g,'继续向下滚动，查看变化。')}</p></div><details class="story-details"><summary>工具、AI 协作与适用范围</summary><p>${s.tools}</p><p>${s.limit}</p><a href="${root.dataset.base}/projects/${project}/">打开完整介绍 ↗</a></details></div></section>`).join('');
 updates=Array.from(document.querySelectorAll<HTMLElement>('.story')).map((section,i)=>mount(section,i));
 document.querySelectorAll<HTMLButtonElement>('[data-step]').forEach(b=>b.onclick=()=>document.getElementById(`stage-${b.dataset.step}`)?.scrollIntoView({behavior:'smooth'}));
 updateAll();
}
function mount(section:HTMLElement,index:number){
 const isTraining=project==='citibike'&&index===3;
 const step=project==='citibike'&&index>3?index-1:index;
 const $=(id:string)=>section.querySelector<HTMLElement>(`[data-ui="${id}"]`)||section.querySelector<HTMLElement>(`#${id}`)!;
 function controls(html:string){$('scene-controls').innerHTML=html}
 function bind(id:string,fn:()=>void){$(id).addEventListener('click',fn)}
function bike(){const scene=$('scene');
if(step===0){let done=false;const draw=()=>{scene.innerHTML=`<div class="scene-grid"><div><p class="board-title">Raw 原始骑行 <span>示例 4 行</span></p>${table(['骑行编号','起点','终点'],[['R01','A','B'],['R02','A','C'],['R02','A','C'],['R03','—','B']],done?['','','bad','bad']:[])}</div><div class="arrow">→</div><div><p class="board-title">Bronze 清洗结果</p>${done?`<div class="rows-play">${table(['骑行编号','起点','终点'],[['R01','A','B'],['R02','A','C']])}</div>`:'<div class="center"><div class="big-value">4 → ?</div><p class="stat-note">保留符合规则的骑行记录</p></div>'}</div></div>`};draw();controls(btn('执行清洗','clean'));bind('clean',()=>{done=!done;draw();$('clean').textContent=done?'重置示例':'执行清洗';$('scene-caption').textContent=done?'重复的 R02 和缺少起点的 R03 被排除，留下 2 条记录。':data[project].stages[0].caption})}
if(step===1){let done=false;const draw=()=>{scene.innerHTML=`<div class="scene-grid"><div class="center"><p class="board-title">一条骑行记录</p><div class="row-flow"><div><div class="big-value">A</div><span class="small-label">08:50 借出</span></div><div class="arrow">→</div><div><div class="big-value">B</div><span class="small-label">09:10 还入</span></div></div><span class="branch">同一条骑行，产生借出与还入两个事件</span></div><div class="arrow">→</div><div><p class="board-title">Silver 站点小时记录</p>${table(['站点','小时','借出','还入'],[['A','08—09',done?'1':'0','0'],['B','09—10','0',done?'1':'0']],done?['hot','hot']:[])}<p class="stat-note">＋ 时间字段　＋ 业务字段　＋ 天气字段</p><span class="branch">Gold：标准化 / PCA → 未接入最终训练</span></div></div>`};draw();controls(btn('按站点与小时汇总','aggregate'));bind('aggregate',()=>{done=!done;draw();$('aggregate').textContent=done?'重置计数':'按站点与小时汇总'})}
if(step===2){scene.innerHTML=`<div class="timeline"><div class="endpoints"><span>较早的时间</span><span>较晚的时间 →</span></div><div class="tiles">${Array.from({length:90},(_,i)=>`<i class="tile" data-tile="${i}"></i>`).join('')}</div><div class="legend"><span>训练 80% · 学习</span><span>验证 10% · 比较</span><span>测试 10% · 评估</span></div></div>`;const color=(time:boolean)=>section.querySelectorAll<HTMLElement>('[data-tile]').forEach((e,i)=>{const n=time?i:(i*37)%90;e.className='tile'+(n>=81?' test':n>=72?' validation':'')});color(false);controls(btn('原版：随机分组','random')+btn('修复：时间分组','time',true));bind('random',()=>{color(false);$('scene-caption').textContent='随机分组：较早和较晚的记录可能同时进入训练、验证与测试。'});bind('time',()=>{color(true);$('scene-caption').textContent='时间分组：较早数据用于训练，之后的数据用于验证和测试。同一小时的站点记录放在同一组。'})}
if(step===3){scene.innerHTML=`<div class="row-flow"><div class="flow-item"><p class="stat-note">示意需求</p><div class="big-value">20<small> 辆</small></div><div class="meter">${'<i></i>'.repeat(20)}</div></div><div class="arrow">−</div><div class="flow-item"><p class="stat-note">当前可用</p><div class="big-value"><span id="available">15</span><small> 辆</small></div><div class="meter" id="bikes"></div></div><div class="arrow">→</div><div class="flow-item"><p class="stat-note">规则建议价</p><div class="big-value price-result">$<span id="price">5.61</span></div><p class="stat-note" id="multiplier"></p></div></div>`;controls('<label for="supply">拖动可用车辆数量</label><input id="supply" type="range" min="10" max="20" value="15"/>');const update=()=>{const n=Number(($('supply') as HTMLInputElement).value);$('available').textContent=String(n);$('price').textContent=(4.49*(1+(20-n)/20)).toFixed(2);$('multiplier').textContent=`$4.49 × ${(1+(20-n)/20).toFixed(2)}`;$('bikes').innerHTML=Array.from({length:20},(_,i)=>`<i class="${i>=n?'empty':''}"></i>`).join('')};$('supply').oninput=update;update()}
if(step===4){scene.innerHTML=`<div style="width:100%"><div class="row-flow"><div class="flow-item">${icon('screen')}<p>站点 A · 08 点</p></div><div class="arrow" id="request-arrow">→</div><div class="flow-item">${icon('data')}<p>已有 CSV / 规则</p></div><div class="arrow">→</div><div class="flow-item">${icon('screen')}<div id="response" class="big-value">—</div></div></div><div class="branch center">离线 Spark 模型　 · · · 　尚未接入这个 API</div></div>`;controls(btn('发送示例请求','request'));bind('request',()=>{$('response').textContent='$5.61';$('response').classList.add('scene-enter');$('scene-caption').textContent='示例响应：站点 A，建议价 5.61 美元。浏览器内演示，不调用真实 API。'})}
if(step===5){scene.innerHTML=`<div class="bar-chart">${[['旧字段＋随机','0.633',90],['去三字段＋随机','0.121',17.2],['去三字段＋时间','0.095',13.5]].map(([n,v,w])=>`<div class="bar-row"><span>${n}</span><div class="bar-track"><div class="bar-fill" style="--value:${w}%"></div></div><strong>${v}</strong></div>`).join('')}<p class="stat-note">借出量 R² · 2.4 万行三组冒烟测试</p></div>`;const chart=scene.innerHTML;let showing=false;controls(btn('查看移除了哪些字段','risk'));$('risk').setAttribute('aria-expanded','false');bind('risk',()=>{showing=!showing;scene.innerHTML=showing?`<div class="risk-explanation scene-enter"><div class="risk-time"><div><strong>08:00</strong><span>开始预测 08—09 点</span></div><span class="risk-time-arrow">→</span><div><strong>09:00 之后</strong><span>目标小时的统计才完整</span></div></div><div class="risk-fields">${[['电动车比例','本小时借出的电动车 ÷ 本小时总借出量'],['会员比例','本小时会员借出量 ÷ 本小时总借出量'],['平均骑行时长','本小时借出骑行的平均时长；还需等骑行结束']].map(([name,why])=>`<article><span class="removed-label">已从修复训练中移除</span><strong>${name}</strong><p>${why}</p></article>`).join('')}</div><p class="risk-conclusion">预测开始时，这三个字段还没有完整结果。</p></div>`:chart;$('risk').textContent=showing?'返回三组成绩对比':'查看移除了哪些字段';$('risk').setAttribute('aria-expanded',String(showing));$('scene-caption').textContent=showing?'移除的是目标小时的实际统计。地图上当前的车辆构成，与目标小时实际借出骑行的比例不是同一个字段。':data[project].stages.at(-1)!.caption;})}}
function adventure(){const scene=$('scene');
if(step===0){let merged=false;const draw=()=>{scene.innerHTML=`<div class="scene-grid"><div><p class="board-title">Internet 直销</p>${table(['订单','商品','收入'],[['I01','自行车','100'],['I02','头盔','50']])}<p class="board-title" style="margin-top:18px">Reseller 经销商</p>${table(['订单','商品','收入'],[['R01','自行车','300']])}</div><div class="arrow">→</div><div><p class="board-title">统一销售明细 <span>UNION ALL</span></p>${merged?`<div class="rows-play">${table(['渠道','订单','商品','收入'],[['直销','I01','自行车','100'],['直销','I02','头盔','50'],['经销商','R01','自行车','300']],['hot','hot',''])}</div>`:'<div class="center"><div class="big-value">2 ＋ 1</div><p class="stat-note">字段对齐，记录上下追加</p></div>'}</div></div>`};draw();controls(btn('合并两张表','merge'));bind('merge',()=>{merged=!merged;draw();$('merge').textContent=merged?'重置示例':'合并两张表'})}
if(step===1){scene.innerHTML=`<div style="width:min(700px,100%)">${table(['明细编号','订单','收入','成本'],[['I01-1','I01','100','60'],['I01-1','I01','100','60'],['R01-1','R01','300','—']])}<div id="quality-note" class="center stat-note" style="margin-top:25px">明确检查键：明细编号</div></div>`;controls(btn('执行检查','check'));bind('check',()=>{scene.querySelectorAll('tbody tr').forEach(r=>r.classList.add('bad'));$('quality-note').textContent='I01-1 出现两次；R01-1 缺少成本。先核对来源，再决定如何处理。';$('scene-caption').textContent='重复订单号不一定有问题；同一订单可以包含多条商品明细。本例检查的是明细编号。'})}
if(step===2){const names=['日期','产品','地区','促销'],keys=['OrderDateKey → DateKey','ProductKey','SalesTerritoryKey','PromotionKey'];const draw=(sel:number)=>{scene.innerHTML=`<div class="mobile-relation"><div><strong>${names[sel]}表</strong><span>${keys[sel]}</span></div><b>↓ 按编号关联</b><div><strong>销售明细表</strong><span>一行＝一条商品记录</span></div><p>说明表 1 条记录 → 多条销售明细</p></div><svg class="network" viewBox="0 0 800 280" role="img" aria-label="四张说明表通过键关联销售明细"><rect class="central" x="290" y="100" width="220" height="80"/><text x="400" y="132" text-anchor="middle">销售明细</text><text class="key" x="400" y="157" text-anchor="middle">一行＝一条商品记录</text>${names.map((n,i)=>{const x=i%2?590:10,y=i<2?10:200;return `<path class="${i===sel?'active-link':'link'}" d="M${x+95} ${y+35} L400 140"/><rect x="${x}" y="${y}" width="190" height="65"/><text x="${x+95}" y="${y+25}" text-anchor="middle">${n}表</text><text class="key" x="${x+95}" y="${y+48}" text-anchor="middle">${keys[i]}</text>`}).join('')}</svg>`;$('scene-caption').textContent=sel===1?'示例：销售明细 ProductKey＝310，匹配产品表的 310，得到“自行车”。':`${names[sel]}表通过 ${keys[sel]} 关联销售明细；说明表的键应唯一。`};controls(names.map((n,i)=>btn(n,`dimension${i}`,true)).join(''));names.forEach((_,i)=>bind(`dimension${i}`,()=>draw(i)));draw(1)}
if(step===3){scene.innerHTML=`<div style="width:100%"><div class="row-flow"><div class="flow-item"><p class="stat-note">收入</p><div class="big-value" id="revenue"></div></div><div class="arrow">−</div><div class="flow-item"><p class="stat-note">样例产品成本</p><div class="big-value" id="cost"></div></div><div class="arrow">＝</div><div class="flow-item"><p class="stat-note">估算毛利</p><div class="big-value price-result" id="profit"></div></div></div><div class="formula"><span>估算毛利率</span><strong id="margin"></strong><span id="division"></span></div></div>`;const calc=(r:number,c:number)=>{$('revenue').textContent=String(r);$('cost').textContent=String(c);$('profit').textContent=String(r-c);$('margin').textContent=((r-c)/r*100).toFixed(1)+'%';$('division').textContent=`＝ ${r-c} ÷ ${r}`};controls(btn('全部渠道','all')+btn('只看直销','internet',true)+btn('只看经销商','reseller',true));bind('all',()=>calc(450,380));bind('internet',()=>calc(150,100));bind('reseller',()=>calc(300,280));calc(450,380)}
if(step===4){scene.innerHTML=`<div class="bar-chart"><div class="bar-row"><span>经销商收入占比</span><div class="bar-track"><div class="bar-fill" style="--value:73.26%"></div></div><strong>73.26%</strong></div><div class="bar-row"><span>经销商毛利占比</span><div class="bar-track"><div class="bar-fill" style="--value:3.75%"></div></div><strong>3.75%</strong></div><p class="stat-note">两条柱分别占全部收入、全部估算毛利的比例。</p></div>`;controls(btn('继续定位到年份与产品','drill',true));bind('drill',()=>{$('scene-caption').textContent='经销商 → 2013 年 → 自行车：出现负估算毛利，值得继续核查售价、折扣与成本口径；尚不能确定因果。'})}
if(step===5){scene.innerHTML=`<div style="width:100%"><div class="report-sheets">${['经营总览','盈利诊断','区域分析'].map((n,j)=>`<div class="sheet"><strong>${n}</strong><div class="fake-line"></div><div class="fake-line" style="width:55%"></div><div class="fake-bars">${[40,75,52,90].map((h,i)=>`<i style="height:${h-j*i*4}%"></i>`).join('')}</div><p class="stat-note">Power BI</p></div>`).join('')}</div><p class="center stat-note" style="margin-top:28px">121,253 条商品明细 → 按订单汇总 → 31,455 张订单 → 工作台</p></div>`;controls(btn('查看两份数据各自用途','outputs',true));bind('outputs',()=>{$('scene-caption').textContent='销售明细支持产品等细分分析；订单汇总满足工作台一行一单的要求。31,455 张订单是汇总结果，不是抽样。'})}}

 if(!isTraining){if(project==='citibike')bike();else adventure();}
 const scene=$('scene');
 let last=-1;
 let animate:(p:number)=>void=()=>{};
 const reveal=(e:HTMLElement|null,p:number,x=0)=>{if(!e)return;e.style.opacity=String(p);e.style.transform=`translate(${x*(1-p)}px,${18*(1-p)}px)`;};
 if(!isTraining&&((project==='citibike'&&step===0)||(project==='adventureworks'&&step===0))){
  const id=project==='citibike'?'clean':'merge';
  controls($('scene-controls').innerHTML);
  // Existing actions remain mounted for deterministic state changes, but scrolling is the trigger.
  $(id).hidden=true;
  // Rebind because the control markup was replaced.
  if(project==='citibike')bike();else adventure();
  $(id).hidden=true;
  animate=p=>{const state=p>.3?1:0;if(state!==last){if(last!==-1||state===1)$(id).click();last=state;}const rows=scene.querySelectorAll<HTMLElement>('.scene-grid>div:last-child tbody tr');rows.forEach((r,i)=>reveal(r,clamp((p-.3-i*.12)*5),-65));};
 }
 if(project==='citibike'&&step===1){
  $('aggregate').click();controls('');
  const note=scene.querySelector('.stat-note')!;
  note.outerHTML=`<div class="feature-additions">${[['时间','小时 · 星期'],['业务','比例 · 时长'],['天气','气温 · 降水']].map(([a,b])=>`<div class="feature-chip"><b>＋ ${a}字段</b><span>${b}</span></div>`).join('')}</div>`;
  animate=p=>{const cells=scene.querySelectorAll('tbody tr');cells[0].children[2].textContent=p>.2?'1':'0';cells[1].children[3].textContent=p>.35?'1':'0';scene.querySelectorAll<HTMLElement>('.feature-chip').forEach((e,i)=>reveal(e,clamp((p-.4-i*.15)*6),60));};
 }
 if(project==='citibike'&&step===2){
  animate=p=>scene.querySelectorAll<HTMLElement>('.tile').forEach((e,i)=>{reveal(e,clamp(p*3-i/90),-20)});
 }
 if(!isTraining&&project==='citibike'&&step===3){let manual=false;$('supply').addEventListener('input',()=>manual=true);animate=p=>{if(manual)return;($('supply') as HTMLInputElement).value=String(20-Math.round(p*10));$('supply').dispatchEvent(new Event('input'));manual=false;};}
 if(project==='citibike'&&step===4){
  controls('');scene.innerHTML=`<div class="api-story"><div class="api-steps">${[['选择站点','A 站 · 08 点'],['发送请求','查询价格'],['读取参考','已有 CSV'],['计算倍率','4.49 × 1.25'],['返回价格','$5.61'],['显示看板','价格建议']].map(([a,b],i)=>`<div class="api-node"><small>0${i+1}</small>${icon(i===2?'data':i===1||i===3?'code':'screen')}<strong>${a}</strong><span>${b}</span></div>`).join('')}</div><div class="api-line"><i></i></div><div class="api-result"><span>A 站 · 08 点</span><strong>$5.61</strong><span>示例价格建议</span></div><p class="branch center">离线 Spark 模型尚未接入 API；当前演示读取 CSV 和价格规则。</p></div>`;
  animate=p=>{scene.querySelectorAll<HTMLElement>('.api-node').forEach((e,i)=>reveal(e,clamp(p*7-i),25));(scene.querySelector('.api-line i') as HTMLElement).style.width=`${p*100}%`;reveal(scene.querySelector('.api-result'),clamp((p-.75)*4));};
 }
 if(project==='adventureworks'&&step===1){$('check').hidden=true;animate=p=>{scene.querySelectorAll<HTMLElement>('tbody tr').forEach((e,i)=>e.classList.toggle('bad',p>.2+i*.15));$('quality-note').textContent=p>.65?'I01-1 编号重复；R01-1 缺少成本。核对来源后再处理。':'检查明细编号与成本字段';};}
 if(project==='adventureworks'&&step===2){animate=p=>{const state=Math.min(3,Math.floor(p*4));if(state!==last){$(`dimension${state}`).click();last=state;}};}
 if(project==='adventureworks'&&step===3){animate=p=>scene.querySelectorAll<HTMLElement>('.flow-item,.formula').forEach((e,i)=>reveal(e,clamp(p*4-i*.65),30));}
 if((project==='citibike'&&step===5)||(project==='adventureworks'&&step===4)){
  if(project==='adventureworks'){controls('');scene.insertAdjacentHTML('beforeend','<div class="drill-path"><span>经销商</span><b>→</b><span>2013 年</span><b>→</b><span>自行车</span><strong>负估算毛利，继续核查</strong></div>');}
  animate=p=>{scene.querySelectorAll<HTMLElement>('.bar-fill').forEach((e,i)=>{e.style.transformOrigin='left';e.style.transform=`scaleX(${clamp(p*2.5-i*.25)})`;});reveal(scene.querySelector('.drill-path'),clamp((p-.6)*3));};
 }
 if(project==='adventureworks'&&step===5){controls('');animate=p=>scene.querySelectorAll<HTMLElement>('.sheet').forEach((e,i)=>reveal(e,clamp(p*3-i*.5),50));}

 const enhanced=isTraining?trainingScene(section):enhanceRealScene(section,project,step,root.dataset.base||'');
 if(enhanced)animate=enhanced;
 if(!$('scene-controls').textContent?.trim()||Array.from($('scene-controls').children).every(e=>(e as HTMLElement).hidden))$('scene-controls').parentElement!.hidden=true;
 let previousProgress=-1;
 const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 return ()=>{const rect=section.getBoundingClientRect();const sticky=section.querySelector<HTMLElement>('.story-sticky')!;const mobile=innerWidth<=760;const raw=mobile?(innerHeight*.8-rect.top)/(rect.height*.9):(24-rect.top)/(rect.height-sticky.offsetHeight);const p=reduce?1:clamp(raw);section.style.setProperty('--progress',String(p));if(p!==previousProgress){animate(p);previousProgress=p;}if(rect.top<innerHeight*.5&&rect.bottom>innerHeight*.5){document.querySelectorAll('[data-step]').forEach((b,i)=>{if(i===index)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});}};
}
function updateAll(){updates.forEach(update=>update());}
let queued=false;addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(()=>{queued=false;updateAll();});}},{passive:true});
addEventListener('resize',updateAll);
document.querySelectorAll<HTMLButtonElement>('[data-project]').forEach(b=>b.onclick=()=>{project=b.dataset.project!;history.replaceState(null,'',`#${project}`);render();window.scrollTo({top:0,behavior:'instant'});});
if(location.hash==='#adventureworks')project='adventureworks';render();
addEventListener('hashchange',()=>{const name=location.hash.slice(1);if(data[name]&&name!==project){project=name;render();}});
